const service_url = 'https://us-east-1.websolr.com/solr/e74f806321cd/select?wt=json&q=';
const image_url = 'https://image.tmdb.org/t/p/w220_and_h330_face/';
const info_url = 'https://www.themoviedb.org/movie/';
const genres = [];
genres[28] = "Action";
genres[12] = "Adventure";
genres[16] = "Animation";
genres[35] = "Comedy";
genres[80] = "Crime";
genres[99] = "Documentary";
genres[18] = "Drama";
genres[10751] = "Family";
genres[14] = "Fantasy";
genres[36] = "History";
genres[27] = "Horror";
genres[10402] = "Music";
genres[9648] = "Mystery";
genres[10749] = "Romance";
genres[878] = "Science Fiction";
genres[10770] = "TV Movie";
genres[53] = "Thriller";
genres[10752] = "War";
genres[37] = "Western";

module.exports = { service_url: service_url, image_url: image_url, info_url: info_url, genres: genres };
